name: clin_sig
type: "column consisting of strings, separated by ',' "
description: |
  This spell visualizes the clinical significance, given in clinvar significance terms (https://www.ncbi.nlm.nih.gov/clinvar/)
example: 
  code: |
    render-table:
      columns: 
        clinical significance:
          spell:
            url: <url>
testdata: data1.tsv
authors:
  - Benjamin Orlik