name: Test3

datasets:
    test:
      path: sign/clin_sig/data3.tsv
      separator: "\t"

views:
  test:
    dataset: test
    render-table:
      columns: 
        Significance Column:
          spell:
            url: sign/clin_sig/spell.yaml